name: volumio
version: '0.1'
summary: The audiophile music player
description: |
  Volumio is an headless audiophile music player, designed to play music with
  the highest possible fidelity. Enjoy your music as you never did before!

grade: devel
confinement: devmode

apps:
  backend:
    command: bin/node $SNAP/lib/node_modules/Volumio2/index.js
    environment:
      DATADIR: $SNAP_COMMON
      BASEDIR: $SNAP/lib/node_modules/Volumio2
      ARCH: $SNAP_ARCH
    plugs:
      - pulseaudio
parts:
  dependencies:
    plugin: nil
    stage-packages:
    - mpd
  volumio-backend:
    plugin: nodejs
    source: .
    build-packages:
      # Build tools
      - g++
      - make
      - python-minimal
      - git

      # Libs
      - libavahi-compat-libdnssd-dev
    # specify remote part build order
      after:
      - alsa
    alsa:
      after: [alsa-lib, alsa-plugins]
    alsa-lib:
      # configflags needed until LP#1766878 is fixed
      configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
      - --disable-alisp
      - --disable-aload
      - --disable-python
      - --disable-rawmidi
      - --disable-static
      - --disable-topology
      - --disable-ucm
      - --enable-symbolic-functions
    alsa-plugins:
      after: [alsa-lib]
      # configflags needed until LP#1766878 is fixed
      configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --disable-arcamav
      - --disable-avcodec
      - --disable-jack
      - --disable-mix
      - --disable-oss
      - --disable-usbstream
      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
      - --disable-static
      - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib
